title: Ángel Marín
logo: /assets/img/angelmarinmahm.jpeg
description: Industrial Chemical Engineer transitioning into tech with a strong foundation in programming. I have hands-on experience in web development, SQL, and Agile environments (SCRUM, XP), as well as implementing enterprise systems like LIMS with SAP connection. I’ve managed the full lifecycle of web solutions from start to finish. Currently looking for a Junior or Trainee Developer role to apply my expertise in Java, JavaScript, Python, SQL, and Power BI.
theme: jekyll-theme-cayman
show_downloads: true 
